name: tela_de_login
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  firebase_database: ^6.1.2
  google_sign_in: ^5.0.1
  firebase_auth: ^1.0.3
  flutter_modular: ^2.0.1
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  connectivity: ^3.0.2
  json_annotation: ^3.1.1
  asuka: ^1.0.4
  string_validator: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.4
  mobx_codegen: ^1.1.2
  modular_codegen: 2.0.1
  build_runner: ^1.11.0
  effective_dart: ^1.3.1
  json_serializable: ^3.5.1

flutter:

  uses-material-design: true

  assets:
    - images/computador.png
    - images/paisagem.png

  fonts:
    - family: Berlin
      fonts:
        - asset: fonts/Berlin-Sans-FB.ttf
          weight: 400